### ISSUE TITLE
Bug:  注解上的timeUnit并没有生效

### ISSUE THREAD

**Issue by John-Chan** [pig-mesh/idempotent-spring-boot-starter#3]
https://github.com/pig-mesh/idempotent-spring-boot-starter/blob/64b57a061965f911945406658e1a3299971915ad/src/main/java/com/pig4cloud/plugin/idempotent/aspect/IdempotentAspect.java#L98

看代码时发现了，一会搞个PR，顺便还有几个NPE之类的小优化

**Comment by lltx** [comment]
FIX
