### ISSUE TITLE
使用阿里redis5.0集群版报错

### ISSUE THREAD

**Issue by LanTianYiJiu01** [pig-mesh/idempotent-spring-boot-starter#6]
org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel

**Comment by lltx** [comment]
阿里云redis cluster 对 redis lua 脚本有限制，暂时不支持

**Comment by lltx** [comment]
https://github.com/redisson/redisson/issues/1538

看一下这个， 控制台配置一下那个参数 设置false
